// server/ui/src/components/settings/index.tsx
import React from "react";

import API from "../../utils/api";
import Const from "../../const";
import ModuleSettings from "../../types/module_settings";
import Config from "../../types/config";
import ConfigCheck from "../../types/config_check";

import Loading from "../loading";
import ModuleSettingsComponent from "./module_settings";
import ConfigCheckComponent from "./config_check";

type State = {
    config :Config | null,
    config_checks: ConfigCheck[] | null,
};

class Settings extends React.Component {
    settings_refresh_interval :number;
    state :State = {
        config: null,
        config_checks: null,
    };

    constructor(props: any) {
        super(props);

        this.settings_refresh_interval = 0;

        this.renderModuleList = this.renderModuleList.bind(this);
    }

    componentDidMount() {
        this.load();

        this.settings_refresh_interval = window.setInterval(this.load.bind(this), Const.DATA_REFRESH);
    }

    componentWillUnmount() {
        clearInterval(this.settings_refresh_interval);
    }

    load() {
        this.getConfig();
        this.checkConfig();
    }

    getConfig() {
        API.Config.get().then(response => {
            this.setState({config: response.data});
        }).catch(error => {
            console.log("Get config error: ", error);
        });
    }

    checkConfig() {
        API.Config.check().then(response => {
            if (Object.keys(response.data).length === 0) {
                this.setState({config_checks: []});
                return;
            }

            this.setState({config_checks: response.data});
        }).catch(error => {
            console.log("Check config error: ", error);
        });
    }

    renderModuleList(title: string | JSX.Element, collection: Array<ModuleSettings>, type: string) {
        let moduleList :Array<ModuleSettings> = [];

        if (!collection) {
            return (
                <div>
                    <h4>{title}</h4>
                    <ul className="uk-list uk-list-striped no-stripes">
                        <li className="uk-text-muted uk-text-center"><i>No {type}s defined in configuration</i></li>
                    </ul>
                </div>
            );
        }

        Object.keys(collection).forEach((key: any) => {
            moduleList.push({
                Name: key,
                Config: collection[key]
            } as ModuleSettings);
        });

        // TODO: Transform module settings to component
        return (
            <div>
                <h4>{title}</h4>
                <ul className="uk-list uk-list-striped no-stripes">
                    {moduleList.map(module =>
                        <li key={module.Name}>
                            <ModuleSettingsComponent
                                type={type}
                                module={module}/>
                        </li>
                    )}
                </ul>
            </div>
        );
    }

    render() {
        if (this.state.config == null || this.state.config_checks == null) {
            return (
                <Loading/>
            );
        }

        return (
            <>
                {this.state.config_checks.length > 0 && (
                    <div className="uk-container">
                        <div className="uk-alert uk-alert-danger" data-uk-alert>
                            <div className="uk-flex uk-flex-middle">
                                <h3 className="uk-margin-remove">Configuration errors</h3>
                                <button className="uk-alert-close" data-uk-close></button>
                            </div>
                            <hr/>
                            <ul>
                                {this.state.config_checks.map((check, index) => (
                                    <ConfigCheckComponent item={check} key={index}/>
                                ))}
                            </ul>
                        </div>
                    </div>
                )}

                <div className="uk-container">
                    <div className="uk-grid uk-grid-small uk-child-width-1-1 uk-child-width-1-2@m" data-uk-grid>
                        <div className="uk-width-1-1">
                            <h3 className="uk-heading-divider">Global settings</h3>
                        </div>

                        <div>
                            <ul className="uk-list uk-list-striped no-stripes">
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Polling interval
                                    </div>
                                    <div>
                                        <code>
                                            {this.state.config.System.CheckInterval}mn
                                        </code>
                                    </div>
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Torrent download attempts limit
                                    </div>
                                    <div>
                                        <code>
                                            {this.state.config.System.TorrentDownloadAttemptsLimit}
                                        </code>
                                    </div>
                                </li>
                            </ul>
                        </div>

                        <div>
                            <ul className="uk-list uk-list-striped no-stripes">
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Interface enabled
                                    </div>
                                    {this.state.config.Interface.Enabled ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Interface port
                                    </div>
                                    <div>
                                        <code>
                                            {this.state.config.Interface.Port}
                                        </code>
                                    </div>
                                </li>
                            </ul>
                        </div>

                        <div>
                            <ul className="uk-list uk-list-striped no-stripes">
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        TV Shows tracking enabled
                                    </div>
                                    {this.state.config.System.TrackShows ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Movie tracking enabled
                                    </div>
                                    {this.state.config.System.TrackMovies ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Automatic show download
                                    </div>
                                    {this.state.config.System.AutomaticShowDownload ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Automatic movie download
                                    </div>
                                    {this.state.config.System.AutomaticMovieDownload ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Preferred media quality
                                    </div>
                                    {this.state.config.System.PreferredMediaQuality ? (
                                        <div>
                                            <code>
                                                {this.state.config.System.PreferredMediaQuality}
                                            </code>
                                        </div>
                                    ) : (
                                        <div>
                                            None
                                        </div>
                                    )}
                                </li>
                            </ul>
                        </div>

                        <div>
                            <ul className="uk-list uk-list-striped no-stripes">
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        TV Shows library path
                                    </div>
                                    <div className="uk-text-small">
                                        <code>
                                            {this.state.config.Library.ShowPath}
                                        </code>
                                    </div>
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Movies library path
                                    </div>
                                    <div>
                                        <code className="uk-text-small">
                                <span className="uk-text-small">
                                    {this.state.config.Library.MoviePath}
                                </span>
                                        </code>
                                    </div>
                                </li>
                            </ul>
                        </div>

                        <div className="uk-width-1-1">
                            <h3 className="uk-heading-divider">Notifications</h3>
                        </div>
                        <div>
                            <ul className="uk-list uk-list-striped no-stripes">
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Notifications enabled
                                    </div>
                                    {this.state.config.Notifications.Enabled ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Notify on new episode
                                    </div>
                                    {this.state.config.Notifications.NotifyNewEpisode ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Notify on download complete
                                    </div>
                                    {this.state.config.Notifications.NotifyDownloadComplete ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                                <li className="uk-flex uk-flex-middle">
                                    <div className="uk-width-expand">
                                        Notify on download failure
                                    </div>
                                    {this.state.config.Notifications.NotifyFailure ? (
                                        <div className="uk-text-success"><i
                                            className="material-icons float-right md-18">check_circle_outline</i></div>
                                    ) : (
                                        <div className="uk-text-danger"><i
                                            className="material-icons float-right md-18">clear</i></div>
                                    )}
                                </li>
                            </ul>
                        </div>

                        <div className="uk-width-1-1">
                            <h3 className="uk-heading-divider">Modules</h3>
                        </div>
                        {this.renderModuleList("Watchlists", this.state.config.Watchlists, "watchlist")}
                        {this.renderModuleList("Providers", this.state.config.Providers, "provider")}
                        {this.renderModuleList("Notifiers", this.state.config.Notifiers, 'notifier')}
                        {this.renderModuleList(<>Indexers <span
                            className="text-muted">(torznab)</span></>, this.state.config.Indexers.torznab, "indexer")}
                        {this.renderModuleList("Downloaders", this.state.config.Downloaders, "downloader")}
                        {this.renderModuleList("Media centers", this.state.config.MediaCenters, "mediacenter")}

                        <div className="uk-width-1-1">
                            <h4 className="uk-heading-divider">About flemzerd</h4>
                            <ul className="uk-list uk-list-striped no-stripes">
                                <li>Version: <code>{this.state.config.Version}</code></li>
                                <li className="uk-text-center uk-padding-small">flemzerd is an Open Source software. For
                                    feature ideas, notifying bugs or contributing, do not hesitate to head to the <a
                                        target="blank" href="https://github.com/macarrie/flemzerd">GitHub repo</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </>
        );
    }
}

export default Settings;

// server/ui/src/app/settings/settings.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable, of } from 'rxjs';
import { HttpClient } from "@angular/common/http";

import { ConfigService } from '../config.service';

@Component({
    selector: 'app-settings',
    templateUrl: './settings.component.html',
    styleUrls: ['./settings.component.scss']
})
export class SettingsComponent implements OnInit {
    config :any;
    trakt_auth :boolean = false;
    trakt_device_code :any;
    trakt_token :any;
    trakt_auth_errors :any;

    constructor(
        private configService :ConfigService,
        private http :HttpClient
    ) {}

    ngOnInit() {
        this.getConfig();
        this.GetTraktToken();
    }

    getConfig() {
        this.configService.getConfig().subscribe(config => {
            this.config = config;
        })
    }

    keys(obj :any) {
        if (obj == undefined) {
            return [];
        }
        return Object.keys(obj);
    }

    startTraktAuth() {
        this.http.get("/api/v1/modules/watchlists/trakt/auth", {observe: 'response'}).subscribe(response => {
            if (response.status == 200) {
                var waitForDeviceCode = setInterval(() => {
                    this.http.get("/api/v1/modules/watchlists/trakt/devicecode", {observe: 'response'}).subscribe(response => {
                        if (response.body["device_code"] != "") {
                            this.trakt_device_code = response.body;
                            clearInterval(waitForDeviceCode);
                            var waitForTraktToken = setInterval(() => {
                                this.GetTraktToken();
                                this.checkTraktAuthErrors();

                                if (this.trakt_auth_errors != null && this.trakt_auth_errors.length != 0) {
                                    this.trakt_auth = false;
                                    clearInterval(waitForTraktToken);
                                    return;
                                }

                                if (this.trakt_token != null && Object.keys(this.trakt_token).length !== 0) {
                                    if (this.trakt_token.access_token != "") {
                                        clearInterval(waitForTraktToken);
                                    }
                                }
                            }, 3000);
                            setTimeout(function() {
                                clearInterval(waitForTraktToken);
                            }, this.trakt_device_code.expires_in * 1000);
                        }
                    });
                }, 2000);
                setTimeout(function() {
                    clearInterval(waitForDeviceCode);
                }, 10000);
                return;
            } else if (response.status == 204) {
                console.log("Trakt auth already done");
            } else {
                console.log("Trakt auth error");
            }
            return;
        });
    };

    checkTraktAuthErrors() {
        this.http.get("/api/v1/modules/watchlists/trakt/auth_errors").subscribe(response => {
            this.trakt_auth_errors = response;
        });
    };

    GetTraktToken() {
        this.http.get("/api/v1/modules/watchlists/trakt/token").subscribe(response => {
                if (response["access_token"] != "") {
                    this.trakt_auth = true;
                    this.trakt_token = response;
                }
        });
    };
}

<div class="container" *ngIf="!config">
    <div class="row">
        <div class="col-12 py-5 text-center">
            <span class="text-muted h4">
                Configuration loading
            </span>
        </div>
    </div>
</div>

<div class="container" *ngIf="config">
    <div class="row">
        <div class="col-12">
            <h3>Global settings</h3>
            <hr />
        </div>

        <div class="col-lg-6 col-sm-12">
            <ul class="list-group mb-3">
                <li class="list-group-item">
                     Polling interval 
                    <span class="float-right">
                        <code>
                            {{ config.System.CheckInterval }}mn
                        </code>
                    </span>
                </li>
                <li class="list-group-item">
                     Torrent download attempts limit 
                    <span class="float-right">
                        <code>
                            {{ config.System.TorrentDownloadAttemptsLimit }}
                        </code>
                    </span>
                </li>
            </ul>
        </div>

        <div class="col-lg-6 col-sm-12">
            <ul class="list-group mb-3">
                <li class="list-group-item">
                     Interface enabled 
                    <span class="float-right text-danger"
                          *ngIf="!config.Interface.Enabled"><i class="material-icons float-right md-18">clear</i></span>
                    <span class="float-right text-success"
                          *ngIf="config.Interface.Enabled"><i class="material-icons float-right md-18">check_circle_outline</i></span>
                </li>
                <li class="list-group-item">
                     Interface port 
                    <span class="float-right">
                        <code>
                            {{ config.Interface.Port }}
                        </code>
                    </span>
                </li>
            </ul>
        </div>

        <div class="col-lg-6 col-sm-12">
            <ul class="list-group mb-3">
                <li class="list-group-item">
                     TV Shows tracking enabled 
                    <span class="float-right text-danger"
                          *ngIf="!config.System.TrackShows"><i class="material-icons float-right md-18">clear</i></span>
                    <span class="float-right text-success"
                          *ngIf="config.System.TrackShows"><i class="material-icons float-right md-18">check_circle_outline</i></span>
                </li>
                <li class="list-group-item">
                     Movie tracking enabled 
                    <span class="float-right text-danger"
                          *ngIf="!config.System.TrackMovies"><i class="material-icons float-right md-18">clear</i></span>
                    <span class="float-right text-success"
                          *ngIf="config.System.TrackMovies"><i class="material-icons float-right md-18">check_circle_outline</i></span>
                </li>
                <li class="list-group-item">
                     Preferred media quality 
                    <span class="float-right text-muted" *ngIf="!config.System.PreferredMediaQuality">
                        None
                    </span>
                    <span class="float-right" *ngIf="config.System.PreferredMediaQuality">
                        <code>
                            {{ config.System.PreferredMediaQuality }}
                        </code>
                    </span>
                </li>
            </ul>
        </div>

        <div class="col-lg-6 col-sm-12">
            <ul class="list-group mb-3">
                <li class="list-group-item">
                     TV Shows library path 
                    <span class="float-right font-italic text-info">
                        <code>
                            {{ config.Library.ShowPath }}
                        </code>
                    </span>
                </li>
                <li class="list-group-item">
                     Movies library path 
                    <span class="float-right font-italic text-info">
                        <code>
                            {{ config.Library.MoviePath }}
                        </code>
                    </span>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h3>Notifications</h3>
            <hr />
        </div>
        <div class="col-lg-6 col-sm-12">
            <ul class="list-group mb-3">
                <li class="list-group-item">
                     Notifications enabled 
                    <span class="float-right text-danger"
                          *ngIf="!config.Notifications.Enabled"><i class="material-icons float-right md-18">clear</i></span>
                    <span class="float-right text-success"
                          *ngIf="config.Notifications.Enabled"><i class="material-icons float-right md-18">check_circle_outline</i></span>
                </li>
                <li class="list-group-item">
                     Notify on new episode 
                    <span class="float-right text-danger"
                          *ngIf="!config.Notifications.NotifyNewEpisode"><i class="material-icons float-right md-18">clear</i></span>
                    <span class="float-right text-success"
                          *ngIf="config.Notifications.NotifyNewEpisode"><i class="material-icons float-right md-18">check_circle_outline</i></span>
                </li>
                <li class="list-group-item">
                     Notify on download complete 
                    <span class="float-right text-danger"
                          *ngIf="!config.Notifications.NotifyDownloadComplete"><i class="material-icons float-right md-18">clear</i></span>
                    <span class="float-right text-success"
                          *ngIf="config.Notifications.NotifyDownloadComplete"><i class="material-icons float-right md-18">check_circle_outline</i></span>
                </li>
                <li class="list-group-item">
                     Notify on download failure 
                    <span class="float-right text-danger"
                          *ngIf="!config.Notifications.NotifyFailure"><i class="material-icons float-right md-18">clear</i></span>
                    <span class="float-right text-success"
                          *ngIf="config.Notifications.NotifyFailure"><i class="material-icons float-right md-18">check_circle_outline</i></span>
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h3>Modules</h3>
            <hr />
        </div>
        <div class="col-lg-6 col-sm-12">
            <h4>Watchlists</h4>
            <ul class="list-group mb-3">
                <li class="list-group-item" *ngFor="let watchlist of keys(config.Watchlists)">
                     {{ watchlist }} 
                    <span *ngIf="watchlist == 'trakt' && trakt_auth"
                    class="sans-serif text-success float-right font-weight-light font-italic">
                        <small>
                            configured
                        </small>
                    </span>
                    <button *ngIf="watchlist == 'trakt' && !trakt_auth"
                    class="btn btn-outline-danger btn-sm float-right font-weight-light"
                    (click)="startTraktAuth()">
                        Connect to trakt.tv
                    </button>
                    <div *ngIf="watchlist == 'trakt'">
                        <div *ngIf="!trakt_auth && trakt_device_code?.device_code">
                            <hr />

                            Enter the following validation code into <a target="_blank" href="{{ trakt_device_code.verification_url }}">{{ trakt_device_code.verification_url }}</a>
                            <h5 class="font-weight-bold text-center text-info mt-2">{{ trakt_device_code.user_code }}</h5>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
        <div class="col-lg-6 col-sm-12">
            <h4>Providers</h4>
            <ul class="list-group mb-3">
                <li class="list-group-item" *ngFor="let provider of keys(config.Providers)">
                    {{ provider }}
                </li>
            </ul>
        </div>
        <div class="col-lg-6 col-sm-12">
            <h4>Notifiers</h4>
            <ul class="list-group mb-3">
                <li class="list-group-item" *ngFor="let notifier of keys(config.Notifiers)">
                     {{ notifier }} 
                </li>
            </ul>
        </div>
        <div class="col-lg-6 col-sm-12">
            <h4>Indexers <span class="text-muted">(torznab)</span></h4>
            <ul class="list-group mb-3">
                <li class="list-group-item" *ngFor="let indexer of keys(config.Indexers.torznab)">
                     {{ config.Indexers.torznab[indexer].name }} 
                    <span class="float-right text-muted">
                        <small>
                            <code> {{ config.Indexers.torznab[indexer].url }} </code>
                        </small>
                    </span>
                </li>
            </ul>
        </div>
        <div class="col-lg-6 col-sm-12">
            <h4>Downloaders</h4>
            <ul class="list-group mb-3">
                <li class="list-group-item" *ngFor="let downloader of keys(config.Downloaders)">
                     {{ downloader }} 
                </li>
            </ul>
        </div>
        <div class="col-lg-6 col-sm-12">
            <h4>Media centers</h4>
            <ul class="list-group mb-3">
                <li class="list-group-item" *ngFor="let mc of keys(config.MediaCenters)">
                     {{ mc }} 
                </li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-12 mt-2">
            <h4>About flemzerd</h4>
        </div>
        <div class="col-12 mb-2">
            <ul class="list-group">
                <li class="list-group-item">Version: <code>{{ config.Version }}</code></li>
                <li class="list-group-item text-center text-muted py-4">flemzerd is an Open Source software. For feature ideas, notifying bugs or contributing, do not hesitate to head to the <a target="blank" href="https://github.com/macarrie/flemzerd">GitHub repo</a></li>
            </ul>
        </div>
    </div>
</div>
