// server/ui/src/app/notification/notification.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { Notification } from '../notification';
import { Const } from '../const';

import { NotificationsService } from '../notifications.service';
import { UtilsService } from '../utils.service';

@Component({
    selector: 'notification',
    templateUrl: './notification.component.html',
    styleUrls: ['./notification.component.scss']
})
export class NotificationComponent implements OnInit {
    @Input() notification :Notification;
    constants :any;

    constructor(
        private notificationsService :NotificationsService,
        private utils :UtilsService
    ) {}

    ngOnInit() {
        this.constants = Const;
    }

    changeReadState(notif :Notification, read :boolean) {
        this.notificationsService.changeReadState(notif, read).subscribe(notif => {
            this.notificationsService.getNotifications();
        });
    }

    getStatusPill(n :Notification) {
        let status :Number = 0;

        switch (n.Type) {
            case Const.NOTIFICATION_NEW_EPISODE:
                status = Const.INFO;
                break;
            case Const.NOTIFICATION_NEW_MOVIE:
                status = Const.INFO;
                break;
            case Const.NOTIFICATION_DOWNLOAD_START:
                status = Const.INFO;
                break;
            case Const.NOTIFICATION_DOWNLOAD_SUCCESS:
                status = Const.OK;
                break;
            case Const.NOTIFICATION_DOWNLOAD_FAILURE:
                status = Const.CRITICAL;
                break;
            case Const.NOTIFICATION_TEXT:
                status = Const.INFO;
                break;
            default:
                status = Const.UNKNOWN;
                break;
        }

        let classes :string = "notif-icon ";

        switch (status) {
            case Const.OK:
                classes += "ok";
                break;
            case Const.WARNING:
                classes += "warning";
                break;
            case Const.CRITICAL:
                classes += "critical";
                break;
            case Const.UNKNOWN:
                classes += "unknown";
                break;
            case Const.INFO:
                classes += "info";
                break;
        }

        return classes;
    }
}

<table *ngIf="notification"
    [class.notification_read]="notification.Read">
    <tr>
        <td [ngClass]="getStatusPill(notification)"><div></div></td>
        <td class="notification_collapse"
            (click)="toggleContent = !toggleContent">
            <a class="btn btn-sm p-0 text-muted">
                <i class="material-icons md-18" *ngIf="!toggleContent">expand_more</i>
                <i class="material-icons md-18" *ngIf="toggleContent">expand_less</i>
            </a>
        </td>
        <td (click)="toggleContent = !toggleContent">
            <span *ngIf="notification.Type == constants.NOTIFICATION_NEW_EPISODE">
                New episode aired: <a routerLink="/episodes/{{ notification.Episode.ID }}"> {{ getShowTitle(notification.Episode.TvShow) }} S{{ utils.formatNumber(notification.Episode.Season) }}E{{ utils.formatNumber(notification.Episode.Number) }}: {{ notification.Episode.Name }}</a>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_NEW_MOVIE">
                New movie: <a routerLink="/movies/{{ notification.Movie.ID }}">{{ getMovieTitle(notification.Movie) }}</a>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_DOWNLOAD_START">
                Download started: 
                <a routerLink="/movies/{{ notification.Movie.ID }}" *ngIf="notification.Movie.ID != 0">{{ getMovieTitle(notification.Movie) }}</a>
                <a routerLink="/episodes/{{ notification.Episode.ID }}" *ngIf="notification.Episode.ID != 0"> {{ getShowTitle(notification.Episode.TvShow) }} S{{ utils.formatNumber(notification.Episode.Season) }}E{{ utils.formatNumber(notification.Episode.Number) }}: {{ notification.Episode.Name }}</a>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_DOWNLOAD_SUCCESS">
                Download success
                <a routerLink="/movies/{{ notification.Movie.ID }}" *ngIf="notification.Movie.ID != 0">{{ getMovieTitle(notification.Movie) }}</a>
                <a routerLink="/episodes/{{ notification.Episode.ID }}" *ngIf="notification.Episode.ID != 0"> {{ getShowTitle(notification.Episode.TvShow) }} S{{ utils.formatNumber(notification.Episode.Season) }}E{{ utils.formatNumber(notification.Episode.Number) }}: {{ notification.Episode.Name }}</a>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_DOWNLOAD_FAILURE">
                Download failure
                <a routerLink="/movies/{{ notification.Movie.ID }}" *ngIf="notification.Movie.ID != 0">{{ getMovieTitle(notification.Movie) }}</a>
                <a routerLink="/episodes/{{ notification.Episode.ID }}" *ngIf="notification.Episode.ID != 0"> {{ getShowTitle(notification.Episode.TvShow) }} S{{ utils.formatNumber(notification.Episode.Season) }}E{{ utils.formatNumber(notification.Episode.Number) }}: {{ notification.Episode.Name }}</a>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_TEXT">
                {{ notification.Title }}
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_NO_TORRENT">
                No torrents found: 
                <a routerLink="/movies/{{ notification.Movie.ID }}" *ngIf="notification.Movie.ID != 0">{{ getMovieTitle(notification.Movie) }}</a>
                <a routerLink="/episodes/{{ notification.Episode.ID }}" *ngIf="notification.Episode.ID != 0"> {{ getShowTitle(notification.Episode.TvShow) }} S{{ utils.formatNumber(notification.Episode.Season) }}E{{ utils.formatNumber(notification.Episode.Number) }}: {{ notification.Episode.Name }}</a>
            </span>
        </td>
        <td class="text-muted text-right">
            <small>
                {{ utils.formatDate(notification.CreatedAt, 'ddd DD MMM hh:mm') }}
            </small>
        </td>
        <td *ngIf="!notification.Read"
            class="notification_action_button text-right"
            (click)="changeReadState(notification, true)">
            <a class="btn btn-sm p-0">
                <i class="material-icons md-18">check</i>
            </a>
        </td>
    </tr>
    <tr *ngIf="toggleContent">
        <td></td>
        <td></td>
        <td colspan="2">
            <span *ngIf="notification.Type == constants.NOTIFICATION_NEW_EPISODE">
                <blockquote class="pl-2">{{ notification.Episode.Overview }}</blockquote>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_NEW_MOVIE">
                <blockquote class="pl-2">{{ notification.Movie.Overview }}</blockquote>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_DOWNLOAD_START">
                <blockquote class="pl-2" *ngIf="notification.Movie.ID != 0">{{ notification.Movie.Overview }}</blockquote>
                <blockquote class="pl-2" *ngIf="notification.Episode.ID != 0">{{ notification.Movie.Overview }}</blockquote>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_DOWNLOAD_SUCCESS">
                <blockquote class="pl-2" *ngIf="notification.Movie.ID != 0">{{ notification.Movie.Overview }}</blockquote>
                <blockquote class="pl-2" *ngIf="notification.Episode.ID != 0">{{ notification.Movie.Overview }}</blockquote>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_DOWNLOAD_FAILURE">
                <blockquote class="pl-2" *ngIf="notification.Movie.ID != 0">{{ notification.Movie.Overview }}</blockquote>
                <blockquote class="pl-2" *ngIf="notification.Episode.ID != 0">{{ notification.Movie.Overview }}</blockquote>
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_TEXT">
                {{ notification.Content }}
            </span>
            <span *ngIf="notification.Type == constants.NOTIFICATION_NO_TORRENT">
                No torrents have been found for media. Try adding new indexers or wait for torrents to be available (for recently released movies or episodes)
            </span>
        </td>
        <td></td>
    </tr>
</table>

// server/ui/src/components/notifications/notification.tsx
import React from "react";
import {Link} from "react-router-dom";

import Helpers from "../../utils/helpers";
import Const from "../../const";

type NotificationType = {
    Title: string,
    Type: number,
}

type Props = {
    item: NotificationType,
};

type State = {
    notification: NotificationType | null,
};

class Notification extends React.Component<Props, State> {
    state: State = {
        notification: null,
    };

    constructor(props: Props) {
        super(props);

        this.state.notification = this.props.item;

        this.getMediaLink = this.getMediaLink.bind(this);
        this.getMediaOverview = this.getMediaOverview.bind(this);
    }

    componentWillReceiveProps(nextProps: Props) {
        this.setState({ notification: nextProps.item });
    }

    getStatusClass() {
        let status = 0;

        if (this.state.notification == null) {
            return 0;
        }

        switch (this.state.notification.Type) {
            case Const.NOTIFICATION_NEW_EPISODE:
                status = Const.INFO;
                break;
            case Const.NOTIFICATION_NEW_MOVIE:
                status = Const.INFO;
                break;
            case Const.NOTIFICATION_DOWNLOAD_START:
                status = Const.INFO;
                break;
            case Const.NOTIFICATION_DOWNLOAD_SUCCESS:
                status = Const.OK;
                break;
            case Const.NOTIFICATION_DOWNLOAD_FAILURE:
                status = Const.CRITICAL;
                break;
            case Const.NOTIFICATION_TEXT:
                status = Const.INFO;
                break;
            case Const.NOTIFICATION_NO_TORRENT:
                status = Const.WARNING;
                break;
            default:
                status = Const.UNKNOWN;
                break;
        }

        let classes = "notif-icon ";

        switch (status) {
            case Const.OK:
                classes += "ok";
                break;
            case Const.WARNING:
                classes += "warning";
                break;
            case Const.CRITICAL:
                classes += "critical";
                break;
            case Const.UNKNOWN:
                classes += "unknown";
                break;
            case Const.INFO:
                classes += "info";
                break;
            default:
                break;
        }

        return classes;
    }

    getMediaLink() {
        if (this.state.notification.Movie.ID) {
            return (
                <Link to={`/movies/${this.state.notification.Movie.ID}`}>{Helpers.getMediaTitle(this.state.notification.Movie)}</Link>
            );
        }
        if (this.state.notification.Episode.ID) {
            return (
                <Link to={`/tvshows/${this.state.notification.Episode.TvShow.ID}/episodes/${this.state.notification.Episode.ID}`}>{Helpers.getMediaTitle(this.state.notification.Episode)}</Link>
            );
        }
    }

    getMediaOverview() {
        if (this.state.notification.Movie.ID) {
            return (
                <blockquote className="uk-text-normal uk-padding-left-small">{this.state.notification.Movie.Overview}</blockquote>
            );
        }
        if (this.state.notification.Episode.ID) {
            return (
                <blockquote className="uk-text-normal uk-padding-left-small">{this.state.notification.Episode.Overview}</blockquote>
            );
        }
    }

    getNotificationTitle() {
        if (this.state.notification.Type === Const.NOTIFICATION_NEW_EPISODE) {
            return (
                <span>
                    New episode aired: {this.getMediaLink()}
                </span>
            );
        }

        if (this.state.notification.Type === Const.NOTIFICATION_NEW_MOVIE) {
            return (
                <span>
                    New movie: {this.getMediaLink()}
                </span>
            );
        }

        if (this.state.notification.Type === Const.NOTIFICATION_DOWNLOAD_START) {
            return (
                <span>
                    Download started: {this.getMediaLink()}
                </span>
            );
        }

        if (this.state.notification.Type === Const.NOTIFICATION_DOWNLOAD_SUCCESS) {
            return (
                <span>
                    Download success: {this.getMediaLink()}
                </span>
            );
        }

        if (this.state.notification.Type === Const.NOTIFICATION_DOWNLOAD_FAILURE) {
            return (
                <span>
                    Download failure: {this.getMediaLink()}
                </span>
            );
        }

        if (this.state.notification.Type === Const.NOTIFICATION_TEXT) {
            return (
                <span>
                    {this.state.notification.Title}
                </span>
            );
        }

        if (this.state.notification.Type === Const.NOTIFICATION_NO_TORRENT) {
            return (
                <span>
                    No torrents found: {this.getMediaLink()}
                </span>
            );
        }
    }

    getNotificationContent() {
        if (this.state.notification.Type === Const.NOTIFICATION_TEXT) {
            return (
                <span>
                    {this.state.notification.Content}
                </span>
            );
        }

        if (this.state.notification.Type === Const.NOTIFICATION_NO_TORRENT) {
            return (
                <span>
                    No torrents have been found for media. Try adding new indexers or wait for torrents to be available (for recently released movies or episodes)
                </span>
            );
        }

        return (
            <span>
                {this.getMediaOverview()}
            </span>
        );
    }

    render() {
        return (
            <li className={this.state.notification.Read ? "read" : ""}>
                <table
                    className={`uk-table-middle notification-table ${this.state.notification.Read ? "notification_read" : ""}`}>
                    <tbody>
                        <tr data-uk-toggle={`target: .notification-detailed-content-${this.state.notification.ID}`}>
                            <td className={`uk-width-auto uk-padding-medium-right notif-icon ${this.getStatusClass()}`}><div></div></td>
                            <td className="uk-width-expand">
                                {this.getNotificationTitle()}
                            </td>
                            <td className="uk-table-shrink uk-text-nowrap uk-text-muted uk-text-right">
                                <small>
                                    {Helpers.formatDate(this.state.notification.CreatedAt, 'ddd DD MMM hh:mm')}
                                </small>
                            </td>
                            {!this.state.notification.Read && (
                                <td className="notification_action_button uk-text-success"
                                    onClick={() => this.props.markRead(this.state.notification.ID)}>
                                    <span data-uk-icon="icon: check"></span>
                                </td>
                            )}
                        </tr>
                        <tr className={`notification-detailed-content-${this.state.notification.ID}`} hidden>
                            <td></td>
                            <td colSpan="2">
                                {this.getNotificationContent()}
                            </td>
                            <td></td>
                        </tr>
                    </tbody>
                </table>
            </li>
        );
    }
}

export default Notification;
